import Head from 'next/head';
import { useState, useEffect } from 'react';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import Schedule from './schedule';
import Classes from './classes';
import Instructors from './instructors';
import Contact from './contact';
import About from './about';

const slideshowImages = [
  '/images/lift.jpg',
  '/images/rope.jpg',
  '/images/yoga.jpg',
];

export default function Home() {
  const [showSchedule, setShowSchedule] = useState(false);
  const [showClasses, setShowClasses] = useState(false);
  const [showInstructors, setShowInstructors] = useState(false);
  const [showContact, setShowContact] = useState(false);
  const [showAbout, setShowAbout] = useState(false);
  const [currentImageIndex, setCurrentImageIndex] = useState(0);
  const [nextImageIndex, setNextImageIndex] = useState(1);

  useEffect(() => {
    const interval = setInterval(() => {
      setCurrentImageIndex((prevIndex) =>
        prevIndex === slideshowImages.length - 1 ? 0 : prevIndex + 1
      );
      setNextImageIndex((prevIndex) =>
        prevIndex === slideshowImages.length - 1 ? 0 : prevIndex + 1
      );
    }, 3000);

    return () => clearInterval(interval);
  }, []);

  const handleMenuButtonClick = (targetState) => {
    setShowSchedule(targetState === 'schedule');
    setShowClasses(targetState === 'classes');
    setShowInstructors(targetState === 'instructors');
    setShowContact(targetState === 'contact');
    setShowAbout(targetState === 'about');
  };

  const renderPageContent = () => {
    if (showSchedule || (!showClasses && !showInstructors && !showContact && !showAbout)) {
      return <Schedule />;
    } else if (showClasses) {
      return <Classes />;
    } else if (showInstructors) {
      return <Instructors />;
    } else if (showContact) {
      return <Contact />;
    } else if (showAbout) {
      return <About />;
    }
    return null;
  };

  return (
    <>
      <Head>
        <title>FireFuel: a fake gym</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.menuBanner}>
          <div className={styles.slideshowContainer}>
            {slideshowImages.map((image, index) => (
              <img
                key={index}
                src={image}
                alt="Slideshow"
                className={`${styles.slideshowImage} ${
                  index === currentImageIndex ? styles.current : ''
                }`}
              />
            ))}
          </div>
          <div className={styles.titleBox}>
            <h1 className={styles.menuBannerTitle}>FitFuel</h1>
            <p className={styles.menuBannerSubtitle}>The gym that fuels you.</p>
          </div>
          <div className={styles.menuBannerContent}>
            <button
              className={styles.menuBannerButton}
              onClick={() => handleMenuButtonClick('classes')}
            >
              Classes
            </button>
            <button
              className={styles.menuBannerButton}
              onClick={() => handleMenuButtonClick('schedule')}
            >
              Schedule
            </button>
            <button
              className={styles.menuBannerButton}
              onClick={() => handleMenuButtonClick('instructors')}
            >
              Instructors
            </button>
            <button
              className={styles.menuBannerButton}
              onClick={() => handleMenuButtonClick('contact')}
            >
              Contact
            </button>
            <button
              className={styles.menuBannerButton}
              onClick={() => handleMenuButtonClick('about')}
            >
              About
            </button>
          </div>
        </div>
        <div className={styles.pageContent}>{renderPageContent()}</div>
      </main>
    </>
  );
}